name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0_pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ad7fa65496954973e566ec982e5d6805e1eae0abdcb21bf2566eee51d3930cd"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
