name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0_pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f2286aa0bf059de0f8436350880134e96cf2ea7e9b50b698817e4f46e8a3f97"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
