name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c5f10240659827f97879d05acedf3d5c8e7e454702e50dd1c2ce14022d6087e"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
