name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0_pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f84ac1c29b792da536bc5d28e9324a799c229de61c8675b106ec108d711b716"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
