name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0_pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cfce40c0f7a0c31427c53956132121f96f73f9c442cc457b899d1cafec32786"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
