name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0_pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96d793d455749cba27a24fb4301ea045a2a0ca1154be90c9c9bc11f7cc0a586b"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
