name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27168bcab49375e6f3a4fd612d1d22884d2719cba29fefff9a3844348fbcb135"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
