name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "127d1b5a148f36193249bd03cc63da5fa874b992e76ec90b2f4c26031c545536"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
