name = "Breakneck"
author = "CrismPack"
version = "4.3.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15e05ef584fecba9182b370685b9684b560ce1a68426870641072c842cd220e0"

[versions]
fabric = "0.16.7"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2","1.21.3"]
