name = "Breakneck"
author = "HaXr"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f4a56c7d1b7fb751d9108e4f5dd7a4aa668e4d09ddfa247b462f26798af4d02"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2", "1.21.3"]
