name = "Breakneck"
author = "HaXr"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de198ecaf4f48c3ca232413d2ab2d3c57511dbdd3214d62f0e6dafb5df0cf3bd"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2", "1.21.3"]
