name = "Breakneck"
author = "CrismPack"
version = "4.3.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08262ed7d0ea091ad02e45631990b76ed48893c006d312c29740af52e349c14"

[versions]
fabric = "0.16.7"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2", "1.21.3"]
