name = "Breakneck"
author = "HaXr"
version = "4.4.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50a268e8dabab904eefb19056ce8a53e96b6ab08dfcef5a8004cf1ecc626cab8"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
