name = "Breakneck"
author = "HaXr"
version = "4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43961366debd6ad9a46c2c41d8201dc043e4054a87f945ce4544a6a63be9fa0a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
