name = "Breakneck"
author = "CrismPack"
version = "2.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db4cd163520029f382d506b5e8d672b1d7497c751677390ba01eb67eb61a1265"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
