name = "Breakneck"
author = "CrismPack"
version = "2.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "530f017def238c75613f8a7787da4e3197146a52bc7ef2248da0ac8d43e685d7"

[versions]
fabric = "0.14.15"
minecraft = "1.19.3"
