name = "Breakneck"
author = "CrismPack"
version = "2.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66e6333898010679d33b1c79d2a82cda0cf4d166159081f5e549f7918cb51190"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
