name = "Breakneck"
author = "CrismPack"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44e3da1feb0d85b1fbb703552d6a3a5b3c8c96266783f2ba558a8bf985271a30"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
