name = "Breakneck"
author = "CrismPack"
version = "2.3.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c02e8ed89f77fc4a491bdf08dbc04e0126f3a4e7c7a04cf485fa41dfa52e72cf"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
