name = "Breakneck"
author = "CrismPack"
version = "2.2.0-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5547b10e79fe002b8e29c64f51318831fac2748d31c7ab1b54ae57a2992038ac"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
