name = "Breakneck"
author = "CrismPack"
version = "2.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a3d1bfeb8e81439ea9e95584851bc2e3e998ad47ee896d22fa8cafa48f63e67"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
