name = "Breakneck"
author = "CrismPack"
version = "2.3.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3acbc93b0d2dc8187f80335b7f3c459db89346da34eaad4fa83bc7edc2fbc4f8"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
