name = "Breakneck-1.20.2"
author = "CrismPack"
version = "3.2.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99e518f19ba58f4f2ff51f23d1c17cbb89693c46101d0889917002937b73c4f4"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
