name = "Breakneck-1.20.2"
author = "CrismPack"
version = "3.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2db0e9d5288481b2a0f100e9b9be73f745b94737bac86297ebb08cd28a32e1ce"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
