name = "Breakneck-1.20.2"
author = "CrismPack"
version = "3.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7de3d8a964cd24fb430034568163149cca77855cb754408af8a74791745e0a07"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
