name = "Breakneck"
author = "CrismPack"
version = "2.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5902a27222039a77d720e89b9228cf656d86fa821afc1ea41f6089db5eeab68"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
