name = "Breakneck-1.20.2"
author = "CrismPack"
version = "3.2.0.pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e4d8a72a015fdce28667af3f2449588e70f5c5e9b02a4b6a97dc22dc78d2460"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"
