name = "Breakneck"
author = "CrismPack"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79c13929143aa6462be271d0cfdb006688c8233cc6620ef98f878726bca8532e"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
