name = "Breakneck"
author = "CrismPack"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ab4c286e2e2f4eedc6e88e209da746fe2c7f982dd8b35b7ea4a567088ce2414"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
