name = "Breakneck-1.20.5"
author = "CrismPack"
version = "3.5.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04f82546cf0f28bc049cb983a4234ae070fb80c74b1f27626dfd4339cbb8076d"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5"
