name = "Breakneck"
author = "CrismPack"
version = "2.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26296855c67b63c799d44612550fd0c4dc5ead17c2c755915664198c9093cdc5"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
