name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8a3e9e012ff97bb0aca08223c07b39f3b60e89898d3bf3754909b467c52f339"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
