name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cb788b77690745099ffc200bb18c5aad73059cd69042366004a03b33aaae6f7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
