name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e9eb39cb57117bf6d4e67f14496f3e28c5d014d81ab7b107997d7d09e589d75"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
