name = "Breakneck-1.20.2"
author = "CrismPack"
version = "3.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab7b060f31eac621c0e67513f0341929db0dba356a4509ae4e724121393469fc"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
