name = "Breakneck"
author = "CrismPack"
version = "1.19.3-pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1af26e67f6918d0ac6639ede5cce494b843a05a8f02e795a4bbfad24a5fca63"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
