name = "Breakneck"
author = "CrismPack"
version = "2.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97bdb4e0c59e82d5c6f86e5a81263c7604aae6d54da3fb457ed3da77f4e45fac"

[versions]
fabric = "0.14.15"
minecraft = "1.19.3"
