name = "Breakneck"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d134e7c8873b764d5cf50a7da5142f002c3d9033f5c46e5faab158ca35c7a189"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
