name = "Breakneck"
author = "CrismPack"
version = "2.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f92333ce11c824ea392620ed3331276f4b4b46020b98fc16363d898ecdb6fee4"

[versions]
fabric = "0.14.15"
minecraft = "1.19.3"
