name = "Breakneck"
author = "CrismPack"
version = "2.2.0-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e846edae6e3c3df81bb87c6e4c7def1746abf1be598998b7b9d7a1c4e2ec2123"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
