name = "Breakneck"
author = "CrismPack"
version = "3.1.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25b0deaf28197a42ff32d2fe1fd8e1ef6c465344a2bbff578456478cba7a92c4"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
