name = "Breakneck-1.20.1"
author = "CrismPack"
version = "3.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5b5d1440c16945baf71326653b7e2a8ad381417b41dc29787c4a063351d88a6"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
