name = "Breakneck"
author = "CrismPack"
version = "3.1.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63792d0686cfdb844ae27363b26173c40bf3deeaf259e32dd748122b18e18473"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
