name = "Breakneck"
author = "CrismPack"
version = "3.1.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "003ce008d12cbcbb45dc4d226555a453061aebff1f0a1f1de0841b77cfafdf56"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
