name = "Breakneck-1.20.5"
author = "CrismPack"
version = "3.5.0.pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3148d21b548096174c307df869e54bf380b0de34ff1d64d3ecb0b5d0e58b4b32"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5"
