name = "Breakneck"
author = "CrismPack"
version = "2.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12b23a0ec7106a58ae26beea55ad7b9f1fb96f93c14be2cb3adac59bee556ad4"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
