name = "Breakneck"
author = "CrismPack"
version = "2.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3018ff9f72bcf3f7b7a3d47fdce7e3b9f87ad515b112e3aafef410587798932"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
