name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fb736b8ce26d07a0b1adc3958727e296970a711c6f98189d0ec7d9263ac3f28"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
