name = "Breakneck"
author = "CrismPack"
version = "2.3.0.pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad88bd14847e72f060c9cece6debdd7cb5847993a0a47805661f03c94faac30b"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
