name = "Breakneck"
author = "CrismPack"
version = "2.2.0-pre4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a67f0d228fdfb895a45f51fd32d8be7a9adfdbbdc463dbdc815d2e1e975afe98"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
