name = "Breakneck"
author = "CrismPack"
version = "2.2.0-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcc12cae7e30ec070dad27ae5969d2deaa132e62a7c88b042e67df8fe88a3bc9"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
