name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0_pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9cf07aca34c7a2f6c1cec5bca8965f8dcff6713a29151ca61c4130b8abc95d4"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
