name = "Breakneck-1.20.5"
author = "CrismPack"
version = "3.5.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e33effa049c02a9cbe53de03bdebb6b93295481df6a350e610165ecaad444f"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5"
