name = "Breakneck"
author = "CrismPack"
version = "2.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "592cde824467b5a2f663ed89dea50e117243268badd9f561c5dae66fe6d04e1a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
