name = "Breakneck"
author = "CrismPack"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeb92b7c2e1ef0f662cf9365a3e83720fc308750768d7cfa1d465a4f40b997e1"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
