name = "Breakneck"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c78c83afaac17da23d56bbf1b6d214c4db1c1339a318bc9f630bdff26291707"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
