name = "Breakneck"
author = "CrismPack"
version = "3.1.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dc7ece0a54edd95ebb2a9f3b46f84da335f64b8e2c924d78fa07a58bf85543c"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
