name = "Breakneck"
author = "CrismPack"
version = "2.3.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9303c98d09876a75043f6080d758aca73b4b51e645e5120294b9b408f396d961"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
