name = "Breakneck"
author = "HaXr"
version = "4.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57be5833f2c671cfdcf2d65d9c922a542bc74500dfe16f0775e43e48481a68a8"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
