name = "Breakneck"
author = "CrismPack"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a19b27e20fd9ea9d5b9ce08d611ae03a9e48a68b0a9e4cbcf62056c34c711801"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
