name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40d336766b936ed106936bc9cc3b50e2be785d1190b50133d51577ad4082ae23"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
