name = "Breakneck"
author = "HaXr"
version = "4.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72881bb87d23c73870bb0028a78fb5ec66799fa1cee96ea1d1522ca1e834617a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
