name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d99ea1978b5eb53bd95d914f9bfe3cd1e92ba67d8af03aaef8dd1fb99c508e65"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
