name = "Breakneck"
author = "CrismPack"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5261673ea3d9284f20d2ee5b02a4f1046a9ed8c9ea60e01475549553c5aa7087"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
