name = "Breakneck-1.20.5"
author = "CrismPack"
version = "3.5.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fef166023f986cdc7f90153d1ee3f4c72d0214662a959a2049adcdbf42e2cb3b"

[versions]
fabric = "0.15.10"
minecraft = "1.20.5"
