name = "Breakneck"
author = "HaXr"
version = "4.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af6edbaeddbd8d22b0e6b33ad5a2add8932a2cd353ca6af3e600e9625c6a8a62"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
