name = "Breakneck"
author = "CrismPack"
version = "2.3.0.pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd43ed16407fb065ba40757ffdd2f36e8ccfd99a1833cb6419e0090ba20480d0"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
