name = "Breakneck-1.20.1"
author = "CrismPack"
version = "3.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba8ffa3c65d59fd1b40f95ec0bf28e7567dadaa4dfa2ef27d05d92924b5def38"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
