name = "Breakneck"
author = "CrismPack"
version = "3.0.0.pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f65ddf095f54656cf7ce231146d415880754ecf3333071e70b42df13df204955"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
