name = "Breakneck"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1038cd6179a5269d7dbc85d9dbfb26958776cd93490a47751c6b12ab2548a2c"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
