name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f4b7ed6106c2c3e40618de588d5aae5e6aa936aa17c8311465aa05c27e622c7"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
