name = "Breakneck"
author = "HaXr"
version = "4.9.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa68b6db366ced1a038d0d77111f9b502341f32199fa4fe84982734de5fc034c"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"

[options]
acceptable-game-versions = []
