name = "Breakneck"
author = "CrismPack"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40a2918837b25780fd342f53c59ab098a341a10110428a79ccc311eb034d2623"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
