name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e76ef0002648d491ee5651091308e0e6473e8f536e5f8d42773bb834a409b7d"

[versions]
fabric = "0.15.1"
minecraft = "1.20.4"
