name = "Breakneck-1.20.1"
author = "CrismPack"
version = "3.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dd10476630567215b24b5207102a781d6f5baa1651e466c9c0aaccbeee96317"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
