name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecf365aa9e8a81fed006dfa79d92e80214d4bb3e6fd1de5bb69eba8663b0ac5e"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
