name = "Breakneck"
author = "CrismPack"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb51797581609dff729bb8db038c7d0379fb721b599984fcaa749f15659eaacb"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
