name = "Breakneck"
author = "CrismPack"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "231dc6d1091d405dff6a3ceb64682562ef9ee8afb80399efec16584465a737f9"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
