name = "Breakneck-1.21"
author = "CrismPack"
version = "4.0.0_pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5c5dc5ce9f1960fcfc3c8519bccae19c75380cb822589d36206a3d4f5dac0e1"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
