name = "Breakneck"
author = "CrismPack"
version = "2.2.0-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77245813cc663173c14a48ec9c3c8ba6c4ee83bf5d71d73bac560d21a8dddd8d"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
