name = "Breakneck-1.20.2"
author = "CrismPack"
version = "3.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e069a19d57dbf35c9f5b0d11c6f53ff8c824fed0ba05fa311debf5f2a48dc37"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
