name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf882c83e36bf94859ab6567ae75e3d789785bd69464d66167a2ae67f1e32e07"

[versions]
fabric = "0.15.1"
minecraft = "1.20.4"
