name = "Breakneck"
author = "HaXr"
version = "4.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "356fe3fcc1f2c0162d21ea8f8593d2d460c8ad2f1d8d492e148b543ad9b85f9a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
