name = "Breakneck"
author = "CrismPack"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26c2aedfcca8cb6ef6317581523a39d4fb1b6d19c88cc05676d91b47e1668a16"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
