name = "Breakneck"
author = "CrismPack"
version = "2.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9af493395da55b0003584558be95b45e2af437b7dc24f85b6105f92c661148fa"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
