name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80e42dd86df6a17ad262405ecbb8a719c287b4df7524e11c15740ada32eded45"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
