name = "Breakneck"
author = "CrismPack"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fadffead3d8a0b9a872624e63f297cf8ba787bebbf0f1de842f4b0f6cc8dbe8a"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
