name = "Breakneck"
author = "CrismPack"
version = "2.2.0-pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c9e4a7b28d1090d9893c9df3adc1b2aba138db2e298a762254603289b5012c8"

[versions]
fabric = "0.14.11"
minecraft = "1.19.3"
