name = "Breakneck"
author = "CrismPack"
version = "2.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25ca60e2e0c17862b91e9bf25c111336fa962afa57761abd1a2b73e89b2eff87"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
