name = "Breakneck"
author = "CrismPack"
version = "2.3.0.pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6e8fb65e64463b75cec7ef6372932023c008b6942b05127ca6fc48d1d433a39"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
