name = "Breakneck"
author = "HaXr"
version = "4.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "730f11c178a781f3f73dee5bb2bb7fdac0cd3da5791e4a81c9e4015218ad4a50"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
