name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c227aa5f6b937281e4edd67af547608c2a4599eed40d5788deece65c3917eae"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
