name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d901eefdf0ecda11b197b77ce5193c04fac5cd49576d91d9b2d0dd09adaf8614"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
