name = "Breakneck"
author = "HaXr"
version = "4.11.0-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25dad5ed9d63a8496c3ace66d4ee37a40d8bbe4f1230be7aaec61eb0c19e8e51"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
