name = "Breakneck"
author = "CrismPack"
version = "2.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "567ffd503bd82d4b9f5dc9bb71bd2f39314a025d046adf57da277c68a7236a0e"

[versions]
fabric = "0.14.17"
minecraft = "1.19.3"
