name = "Breakneck"
author = "CrismPack"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0016b266bb9e2eb9e33f1c2d64418160412ce21558dc9acdc6bb6038bc9805d"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
