name = "Breakneck"
author = "CrismPack"
version = "2.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31d8f356d795356970a2811d139b91c98f5c808de9085035cc8049a00550f0cb"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
