name = "Breakneck-1.20.4"
author = "CrismPack"
version = "3.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dbce0a42c36fed988c6c60a0e3263fed8e10f566465b1053cbc11974660ad8e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"
