name = "Breakneck"
author = "HaXr"
version = "4.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "700f513571725b93bf172a3bc569a3eef28a52286867dc643e1372a84c17b5c3"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.4"]
