name = "Breakneck-1.20.2"
author = "CrismPack"
version = "3.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78f7dd2cc6e5abedb94b68399ab75d0a1a54352b00bc6d8978ddc326219a682d"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
