name = "Breakneck-1.21"
author = "CrismPack"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0d870e36a98d4461a661cc59a05113c0e4b15492a09bb9b86cf65b972490747"

[versions]
fabric = "0.16.0"
minecraft = "1.21.1"
