name = "Breakneck-1.21"
author = "CrismPack"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a05027b3945f91f2a1890080601ce8da242894bba2590b5b2957c3d31f8f43a"

[versions]
fabric = "0.16.0"
minecraft = "1.21.1"
