name = "Breakneck-1.21.1"
author = "CrismPack"
version = "4.1.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "151abeecfe92e09d5b70ada913e4f9237ab8797578fd7d7029949b5d6422217f"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
