name = "Breakneck-1.21.1"
author = "CrismPack"
version = "4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d059d8215e5cc5d55dc3bc6f71ec0178460fa7c3c4791ff6f917117ebc9ae62a"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
