name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb14ef7486c793d0e8c33aabac9205a76f852d6fb399eec71b2b2471770bed35"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
