name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e67016f69d4e39be4851b5aac40006452a75314f5940590d19e79f37ae1e6e5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
