name = "Breakneck-1.20.6"
author = "CrismPack"
version = "3.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a66c92ffd018c1d00d9a1413cc79e6495b8494ee5eba69452b97f5dddc5d4e2b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
