# The library to use for game controller input. You can change this if you are having problems detecting game controllers.
# Please note that changing from the default library may disable some feature in Controllable, only use this as a last resort
# Valid values: GLFW, SDL2
inputLibrary = "SDL2"

# In-game related options. These can be changed in game instead of config!
[options]
	# If enabled, hotbar will render closer to the center of the screen like on console.
	# Valid values: true, false
	consoleHotbar = false