name: Automatically publish to Modrinth and CurseForge

on:
  release:
    types: [published]

env:
  VERSION_TYPE: beta
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

jobs:
  publish-to-curseforge:
    if: github.repository_owner == 'CrismPack'
    runs-on: ubuntu-24.04
    environment: github-actions
    steps:
    - name: Download pack files
      uses: robinraju/release-downloader@v1.10
      id: download-files
      with:
        fileName: "*.zip"
        latest: true
        tarBall: false
        zipBall: false
        preRelease: true
  
    - name: Publish to CurseForge
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        name: Breakneck v${{ steps.download-files.outputs.tag_name }} for ${{ vars.MC_VERSION }}
        # version-type: "${{ VERSION_TYPE }}"
        changelog-file: Modrinth Release.md

        curseforge-id: 882472
        curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"
        curseforge-files: '*.zip'
        loaders: fabric
        game-versions: ${{ vars.MC_VERSION }}
        

  publish-to-modrinth:
    if: github.repository_owner == 'CrismPack'
    runs-on: ubuntu-24.04
    environment: github-actions
    steps:
    - name: Download pack files
      uses: robinraju/release-downloader@v1.10
      id: download-files
      with:
        fileName: "*.mrpack"
        latest: true
        tarBall: false
        zipBall: false
        preRelease: true
  
    - name: Publish to Modrinth
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        name: Breakneck v${{ steps.download-files.outputs.tag_name }} for ${{ vars.MC_VERSION }}
        # version-type: "${{ VERSION_TYPE }}"
        changelog-file: "Modrinth Release.md"

        modrinth-id: qPrWu8wn
        modrinth-token: "${{env.MODRINTH_TOKEN}}"
        modrinth-files: '*.mrpack'
        loaders: fabric
        game-versions: ${{ vars.MC_VERSION }}